-- DROP DATABASE VINICOLA;

CREATE DATABASE VINICOLA;
USE VINICOLA;

CREATE TABLE EMPRESA (
    IDEMPRESA INT PRIMARY KEY AUTO_INCREMENT,
    NOME_EMPRESA VARCHAR(40),
    CNPJ CHAR(19),
    NOME_FUNC VARCHAR(45),
    TEL1 VARCHAR(15),
    TEL2 VARCHAR(15),
    CEP CHAR(9),
    EMAIL VARCHAR(60),
    SENHA VARCHAR(20)
)  AUTO_INCREMENT=10;

CREATE TABLE TIPO_VINHO (
    IDTIPO_VINHO INT PRIMARY KEY AUTO_INCREMENT,
    TIPO_VINHO VARCHAR(45),
    TEMP_MAX DECIMAL(3 , 1 ),
    TEMP_MIN DECIMAL(3 , 1 ),
    UMID_MAX DECIMAL(3 , 1 ),
    UMID_MIN DECIMAL(3 , 1 )
)  AUTO_INCREMENT=100;

CREATE TABLE LOGIN (
    FKEMPRESA INT,
    FOREIGN KEY (FKEMPRESA)
        REFERENCES EMPRESA (IDEMPRESA),
    IDLOGIN INT,
    PRIMARY KEY (FKEMPRESA , IDLOGIN),
    EMAIL VARCHAR(45),
    SENHA VARCHAR(20)
);

CREATE TABLE ARMAZEM (
    IDARMAZEM INT PRIMARY KEY AUTO_INCREMENT,
    FKEMPRESA INT,
    FOREIGN KEY (FKEMPRESA)
        REFERENCES EMPRESA (IDEMPRESA),
    TIPO_ARMAZEM VARCHAR(45),
    FKTIPO_VINHO INT,
    FOREIGN KEY (FKTIPO_VINHO)
        REFERENCES TIPO_VINHO (IDTIPO_VINHO)
)  AUTO_INCREMENT=300;

CREATE TABLE SENSORES (
    IDSENSORES INT PRIMARY KEY AUTO_INCREMENT,
    FKARMAZEM INT,
    FOREIGN KEY (FKARMAZEM)
        REFERENCES ARMAZEM (IDARMAZEM)
)  AUTO_INCREMENT=400;

CREATE TABLE REGISTROS (
    FKSENSOR INT,
    FOREIGN KEY (FKSENSOR)
        REFERENCES SENSORES (IDSENSORES),
    IDREGISTROS INT,
    PRIMARY KEY (FKSENSOR , IDREGISTROS),
    REGISTRO_TEMP DECIMAL(3 , 1 ),
    REGISTRO_UMID DECIMAL(3 , 1 ),
    REGISTRO_MOMENT DATETIME
);

CREATE TABLE FALE_CONOSCO (
    IDFALE INT PRIMARY KEY AUTO_INCREMENT,
    NOME VARCHAR(45),
    EMAIL VARCHAR(45),
    ASSUNTO VARCHAR(45),
    DESCRICAO VARCHAR(255)
)  AUTO_INCREMENT=500;

INSERT INTO EMPRESA (NOME_EMPRESA, CNPJ, NOME_FUNC, TEL1, TEL2, CEP, EMAIL, SENHA) VALUES 
('EMPRESA A', '12.369.852/0001-89', 'Carlos Bastos Silva', '(11)7857-8009', '(11)98553-8023', '04678-090','empresaA@sac.com.br', '1234'),
('EMPRESA B', '20.395.678/0001-90', 'Vitória Maria','(11)4444-5532', '(11)94444-6666', '12345-697','empresaB@sac.com.br', '1234'),
('EMPRESA C', '31.345.788/0001-91', 'Regina Flores','(11)4478-8675', '(11)94456-1234', '05645-786','empresaC@sac.com.br', '1234'),
('EMPRESA D', '39.785.999/0001-92', 'Sophie Silva','(11)4480-9898', '(11)99090-7676', '03221-990','empresaD@sac.com.br', '1234');

INSERT INTO FALE_CONOSCO (NOME, EMAIL, ASSUNTO, DESCRICAO) VALUES 
('Beatriz Moreira', 'empresaA@sac.com.br', 'Acesso ao Portal', 'Tem uma descrição aqui'),
('Luana Guimarões', 'empresaB@sac.com.br', 'Dúvida sobre dashboard', 'Tem uma descrição aqui'),
('Vitor Coge', 'empresaC@sac.com.br', 'Erro no Sensor', 'Tem uma descrição aqui'),
('Luana Guimarões', 'empresaD@sac.com.br', 'Falha no Site', 'Tem uma descrição aqui');

INSERT INTO TIPO_VINHO (TIPO_VINHO, TEMP_MAX, TEMP_MIN, UMID_MAX, UMID_MIN) VALUES 
('Espumantes', '10.1', '6.5', '60', '75'),
('Tinto Tinto', '18.2', '14.8', '65', '78'),
('Tinto Verde', '17.9', '11.7', '62', '72'),
('Tinto Branco', '18.2', '12.8', '69', '78');

INSERT INTO LOGIN (FKEMPRESA, IDLOGIN, EMAIL, SENHA) VALUES 
(10, 1,'empresaA@sac.com.br', '1234'),
(11, 2, 'empresaB@sac.com.br', '1234'),
(12, 3, 'empresaC@sac.com.br', '1234'),
(13, 4, 'empresaD@sac.com.br', '1234');

INSERT INTO  ARMAZEM (TIPO_ARMAZEM, FKEMPRESA, FKTIPO_VINHO) VALUES 
('Armazém 1', 10, 100),
('Armazém 2', 11, 101),
('Armazém 3', 12, 102),
('Armazém 4', 13, 103);

INSERT INTO  SENSORES (FKARMAZEM) VALUES 
(300),
(301),
(302),
(303);

INSERT INTO  REGISTROS VALUES 
(400, 1, '12.4', '65', '2022-04-21 10:00:00'),
(401, 2, '13.7', '62', '2022-11-09 17:30:00'),
(402, 3, '15.7', '60', '2022-11-09 23:00:00'),
(403, 4, '11.6', '59', '2022-11-09 04:30:00');

/*SELECT * FROM EMPRESA;
SELECT * FROM LOGIN;
SELECT * FROM FALE_CONOSCO;
SELECT * FROM TIPO_VINHO;
SELECT * FROM ARMAZEM;
SELECT * FROM SENSORES;
SELECT * FROM REGISTROS;
*/
SELECT 
    LOGIN.EMAIL,
    LOGIN.SENHA,
    EMPRESA.NOME_EMPRESA,
    EMPRESA.CNPJ,
    EMPRESA.NOME_FUNC,
    EMPRESA.TEL1,
    EMPRESA.TEL2,
    EMPRESA.CEP
FROM
    LOGIN,
    EMPRESA
WHERE
    FKEMPRESA = IDEMPRESA;

SELECT 
    ARMAZEM.TIPO_ARMAZEM,
    EMPRESA.NOME_EMPRESA,
    EMPRESA.CNPJ,
    EMPRESA.NOME_FUNC,
    EMPRESA.TEL1,
    EMPRESA.TEL2,
    EMPRESA.CEP
FROM
    ARMAZEM,
    EMPRESA
WHERE
    FKEMPRESA = IDEMPRESA;

SELECT 
    ARMAZEM.TIPO_ARMAZEM,
    ARMAZEM.TIPO_ARMAZEM,
    EMPRESA.NOME_EMPRESA,
    EMPRESA.CNPJ,
    EMPRESA.NOME_FUNC,
    EMPRESA.TEL1,
    EMPRESA.TEL2,
    EMPRESA.CEP,
    TIPO_VINHO.TIPO_VINHO,
    TIPO_VINHO.TEMP_MAX,
    TIPO_VINHO.TEMP_MIN,
    TIPO_VINHO.UMID_MAX,
    TIPO_VINHO.UMID_MIN
FROM
    ARMAZEM,
    EMPRESA,
    TIPO_VINHO
WHERE
    FKEMPRESA = IDEMPRESA
        AND FKTIPO_VINHO = IDTIPO_VINHO;

SELECT 
    ARMAZEM.TIPO_ARMAZEM,
    TIPO_VINHO.TIPO_VINHO,
    TIPO_VINHO.TEMP_MAX,
    TIPO_VINHO.TEMP_MIN,
    TIPO_VINHO.UMID_MAX,
    TIPO_VINHO.UMID_MIN
FROM
    ARMAZEM,
    TIPO_VINHO
WHERE
    FKTIPO_VINHO = IDTIPO_VINHO;
    
SELECT 
    SENSORES.IDSENSORES,
    ARMAZEM.TIPO_ARMAZEM,
    TIPO_VINHO.TIPO_VINHO,
    TIPO_VINHO.TEMP_MAX,
    TIPO_VINHO.TEMP_MIN,
    TIPO_VINHO.UMID_MAX,
    TIPO_VINHO.UMID_MIN
FROM
    SENSORES,
    ARMAZEM,
    TIPO_VINHO
WHERE
    FKARMAZEM = IDARMAZEM
        AND FKTIPO_VINHO = IDTIPO_VINHO;
SELECT * FROM SENSORES, REGISTROS;

SELECT 
    SENSORES.IDSENSORES,
    REGISTROS.REGISTRO_TEMP,
    REGISTROS.REGISTRO_UMID,
    REGISTROS.REGISTRO_MOMENT
FROM
    SENSORES,
    REGISTROS
WHERE
    FKSENSOR = IDSENSORES;


/*SELECT * FROM LOGIN, EMPRESA WHERE FKEMPRESA = IDEMPRESA;
SELECT * FROM ARMAZEM, EMPRESA WHERE FKEMPRESA = IDEMPRESA;
SELECT * FROM ARMAZEM, TIPO_VINHO WHERE FKTIPO_VINHO = IDTIPO_VINHO;
SELECT * FROM SENSORES, ARMAZEM, TIPO_VINHO WHERE FKARMAZEM = IDARMAZEM AND FKTIPO_VINHO = IDTIPO_VINHO;
SELECT * FROM SENSORES, REGISTROS WHERE FKSENSOR = IDSENSORES;
*/
/*SELECT * FROM LOGIN, EMPRESA WHERE FKEMPRESA = IDEMPRESA AND EMPRESA.EMAIL LIKE '%empresaA@sac.com.br';

SELECT * FROM LOGIN, EMPRESA WHERE FKEMPRESA = IDEMPRESA AND NOME_EMPRESA = 'EMPRESA D';

SELECT DESCRICAO FROM FALE_CONOSCO;

SELECT IDFALE, DESCRICAO FROM FALE_CONOSCO WHERE IDFALE = 502;
*/


-- Grupo 7 
